#!/bin/bash

declare -a PRAISE_ADJECTIVES=(
  'beautiful'
  'sophisticated'
  'poetic'
  'noble'
  'talented'
  'brilliant'
  'powerful'
  'perfect'
  'cunning'
  'chestnut-haired'
  'thoughtful'
  'kind'
  'rule-breaking'
  'glowing'
  'sweet'
  'innocent'
  'pretty'
  'amazing'
  'opalescent'
  'rainbow infused'
  'beautiful, naive'
  'cunning'
  'tricky'
  'sassy'
  'smooth coated'
  'majestic'
)

declare -a PRAISE_NOUNS=(
  'newborn baby'
  'land mermaid'
  'musk ox'
  'sunflower'
  'unicorn nurse'
  'spinster'
  'sunfish'
  'sun goddess'
  'tropical fish'
  'tree shark'
  'space unicorn'
  'mannequin'
  'sea otter'
  'flamingo'
)

function _praise {
  RANDOM=$$$(date +%s)

  ADJECTIVE=${PRAISE_ADJECTIVES[$RANDOM % ${#PRAISE_ADJECTIVES[@]} ]}
  NOUN=${PRAISE_NOUNS[$RANDOM % ${#PRAISE_NOUNS[@]} ]}
  
  NAME=$(whoami)

  echo "Have a wonderful day ${NAME}, you ${ADJECTIVE} ${NOUN}!"
}

_praise

